### PR TITLE
feat: Customise prefix for commit messages created by dependabot

### PR DESCRIPTION
**Pull request by sebastianczech**
## Description

PR customises commit messages created by `dependabot` while updating `github-actions`.

## Motivation and Context

In https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/pull/73 title was manually changed in order to trigger release, in https://github.com/PaloAltoNetworks/terraform-modules-vmseries-ci-workflows/pull/78 there was no change of title and no release was triggered. For future to avoid manual step we can:
- do release with commit containing prefix `chore` - it can be achieved by changing release rules according to https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#releaserules
- change prefix added by `dependabot` - it can be done by adding `prefix` to `dependabot.yml` file according to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message

In PR second solution was chosen, because it allows in future to add commits with `chore` prefix, which are not changing anything in code and should not trigger release.

By purpose invalid prefix `CHANGEME` is configured in order to put correct one - if there are breaking changes, then new minor version should be created, but if there are no breaking changes, then only patch version is required.

## How Has This Been Tested?

Code will be tested next time `dependabot` creates PR.

If that change will work correctly, later it can be applied for other repositories:
* [terraform-aws-vmseries-modules](https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules)
* [terraform-azurerm-vmseries-modules](https://github.com/PaloAltoNetworks/terraform-azurerm-vmseries-modules)
* [terraform-google-vmseries-modules](https://github.com/PaloAltoNetworks/terraform-google-vmseries-modules)

## Types of changes

- New feature (non-breaking change which adds functionality)

## Checklist

- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [x] All new and existing tests passed.

### CODE REVIEW

**Review by FoSix — APPROVED** [review]

**Review by FoSix — COMMENTED** [review]
@sebastianczech  maybe it would be good to change this from `feat` to `chore` or `ci`. It's not a change to the code, so no  need for a new release

**Comment by sebastianczech** [comment]
> @sebastianczech maybe it would be good to change this from `feat` to `chore` or `ci`. It's not a change to the code, so no need for a new release

@FoSix I added by purpose `feat` because I wanted also trigger release for changes from #78 , #77 and #75. Can I leave it as it is ?

**Comment by michalbil** [comment]
I'd opt to use a different prefix than "fix" - dependency update is not really one.

**Comment by pimielowski** [comment]
I also believe that `chore ` fit better here.

**Review by pimielowski — APPROVED** [review]

**Comment by sebastianczech** [comment]
If we use `chore`, then without changing release rules we will not have new release built.

For repository `terraform-modules-vmseries-ci-workflows` if we update some GitHub action (like `tj-actions/changed-files`) we need to create new release - this release package is used in workflows for VM-Series modules e.g.  `terraform-aws-vmseries-modules` e.g.: 

https://github.com/PaloAltoNetworks/terraform-aws-vmseries-modules/blob/5fbca48d51b5bf8817c02623a7a1129679ac1839/.github/workflows/pr_ci.yml#L23-L26

For other repositories like `terraform-aws-vmseries-modules` we have dependabot only for Python packages (so only `pre-commit` currently), so release is not required when we update dependencies.

Personally I preferred option 1 option from PR description (_do release with commit containing prefix chore - it can be achieved by changing release rules according to https://github.com/semantic-release/commit-analyzer?tab=readme-ov-file#releaserules_), but after consulting this subject with @FoSix , option 2 was selected (_change prefix added by dependabot - it can be done by adding prefix to dependabot.yml file according to https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#commit-message_)

**Pull request merged**
